version: '3.7'
services:
  scale:
    container_name: scale_mamba
    build:
      context: .
      network: host

  coordinator:
    image: gpikra/scalemamba:v1
    command: python coordinator.py        
    network_mode: host

  player:
    image: gpikra/scalemamba:v1
    entrypoint: python player.py
    network_mode: host
  
  client:
    image: gpikra/scalemamba:v1
    entrypoint: python client.py
    network_mode: host
