version: '3.7'
services:
  SCALE:
    container_name: SCALE
    image: SCALE:latest
    build:
      context: ./
    ports:
      - ${PORT}:${PORT}
    networks:
      - SCALE

networks:
  SCALE:
    name: SCALE
