version: '3.7'
services:
  scale:
    container_name: scale_mamba
    build:
      context: .
      network: host

  # coordinator_bash:
  #   image: gpikra/scalemamba:v1
  
  coordinator:
    image: gpikra/scalemamba:v1
    command: python coordinator.py        
    network_mode: host
    working_dir: /SCALE-MAMBA
    # volumes:
    #   - .:/SCALE-MAMBA

  player:
    image: gpikra/scalemamba:v1
    entrypoint: python player.py
    network_mode: host
    working_dir: /SCALE-MAMBA
    volumes:
      - ./player_auxilliary.py:/SCALE-MAMBA/player_auxilliary.py

  client:
    image: gpikra/scalemamba:v1
    entrypoint: python client.py
    network_mode: host
    working_dir: /SCALE-MAMBA
    volumes:
      - ./dataset:/SCALE-MAMBA/dataset
      - ./client.py:/SCALE-MAMBA/client.py
