FROM gpikra/scalemamba:v1

WORKDIR /SCALE-MAMBA
COPY ./logistic_regressor.py /SCALE-MAMBA/logistic_regressor.py
COPY ./requirements.txt /SCALE-MAMBA/requirements.txt
RUN pip install -r requirements.txt